output "private_subnets" {
  description = "kubectl config as generated by the module."
  value       = module.vpc.private_subnets
}

output "vpc_id" {
  description = "kubectl config as generated by the module."
  value       = module.vpc.vpc_id
}
